import test from "node:test";
import assert from "node:assert";
import { execSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { syncChangelogRollovers } from "../changelog-rollover.mjs";

function withGitRepo(builder) {
  const repo = mkdtempSync(join(tmpdir(), "daf-changelog-rollover-"));
  try {
    execSync("git init", { cwd: repo });
    execSync("git config user.name deuk-agent", { cwd: repo });
    execSync("git config user.email deuk-agent@example.com", { cwd: repo });
    return builder(repo);
  } finally {
    rmSync(repo, { recursive: true, force: true });
  }
}

function writeText(file, value) {
  writeFileSync(file, value, "utf8");
}

function writeInitialReleaseState(repo) {
  writeText(join(repo, "package.json"), JSON.stringify({
    name: "deuk-agent-flow",
    version: "4.2.1"
  }, null, 2));
  writeText(join(repo, "CHANGELOG.md"), [
    "# Changelog",
    "",
    "All notable changes to this project will be documented in this file.",
    "",
    "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).",
    "",
    "## [Unreleased]",
    "",
    "### Fixed",
    "- **release:** unresolved unreleased fix should be carried to next version.",
    "",
    "## [4.2.1] - 2026-05-10",
    "",
    "### Fixed",
    "- existing release note.",
    ""
  ].join("\n"));
  writeText(join(repo, "CHANGELOG.ko.md"), [
    "# 변경 이력 (Changelog)",
    "",
    "이 프로젝트의 모든 주목할 만한 변경 사항은 이 파일에 기록됩니다.",
    "",
    "## [Unreleased]",
    "",
    "### 수정됨 (Fixed)",
    "- **release:** 이전 버전에서 남긴 미반영 항목.",
    "",
    "## [4.2.1] - 2026-05-10",
    "",
    "### 수정됨 (Fixed)",
    "- 기존 릴리스 항목.",
    ""
  ].join("\n"));

  execSync("git add package.json CHANGELOG.md CHANGELOG.ko.md", { cwd: repo });
  execSync('git commit -m "chore: seed changelog snapshot"', { cwd: repo });
}

test("syncChangelogRollovers fills generated release sections from previous Unreleased notes", () => {
  withGitRepo((repo) => {
    writeInitialReleaseState(repo);

    writeText(join(repo, "package.json"), JSON.stringify({
      name: "deuk-agent-flow",
      version: "4.2.2"
    }, null, 2));
    writeText(join(repo, "CHANGELOG.md"), [
      "# Changelog",
      "",
      "All notable changes to this project will be documented in this file.",
      "",
      "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).",
      "",
      "## [Unreleased]",
      "",
      "### Fixed",
      "- _Nothing to release yet._",
      "",
      "## [4.2.2] - 2026-05-10",
      "",
      "_generated by bump command_",
      ""
    ].join("\n"));
    writeText(join(repo, "CHANGELOG.ko.md"), [
      "# 변경 이력 (Changelog)",
      "",
      "이 프로젝트의 모든 주목할 만한 변경 사항은 이 파일에 기록됩니다.",
      "",
      "## [Unreleased]",
      "",
      "### 수정됨 (Fixed)",
      "- _미공개 누적 변경 없음._",
      "",
      "## [4.2.2] - 2026-05-10",
      "",
      "_bump generated_",
      ""
    ].join("\n"));

    const changed = syncChangelogRollovers({ rootDir: repo, version: "4.2.2", date: "2026-05-10" });
    const currentEnglish = readFileSync(join(repo, "CHANGELOG.md"), "utf8");
    const currentKorean = readFileSync(join(repo, "CHANGELOG.ko.md"), "utf8");

    assert.equal(changed, true);
    assert.match(currentEnglish, /## \[4\.2\.2\] - 2026-05-10[\s\S]*### Fixed[\s\S]*\*\*release:\*\* unresolved unreleased fix should be carried to next version\./);
    assert.match(currentKorean, /## \[4\.2\.2\] - 2026-05-10[\s\S]*### 수정됨 \(Fixed\)[\s\S]*\*\*release:\*\* 이전 버전에서 남긴 미반영 항목\./);
    assert.equal(currentEnglish.includes("_generated by bump command_"), false);
    assert.equal(currentKorean.includes("_bump generated_"), false);
  });
});

test("syncChangelogRollovers preserves generated release section when it already contains real entries", () => {
  withGitRepo((repo) => {
    writeInitialReleaseState(repo);

    writeText(join(repo, "package.json"), JSON.stringify({
      name: "deuk-agent-flow",
      version: "4.2.2"
    }, null, 2));
    writeText(join(repo, "CHANGELOG.md"), [
      "# Changelog",
      "",
      "All notable changes to this project will be documented in this file.",
      "",
      "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).",
      "",
      "## [Unreleased]",
      "",
      "### Fixed",
      "- _Nothing to release yet._",
      "",
      "## [4.2.2] - 2026-05-10",
      "",
      "### Fixed",
      "- **cli:** existing release note should stay.",
      ""
    ].join("\n"));
    writeText(join(repo, "CHANGELOG.ko.md"), [
      "# 변경 이력 (Changelog)",
      "",
      "이 프로젝트의 모든 주목할 만한 변경 사항은 이 파일에 기록됩니다.",
      "",
      "## [Unreleased]",
      "",
      "### 수정됨 (Fixed)",
      "- _미공개 누적 변경 없음._",
      "",
      "## [4.2.2] - 2026-05-10",
      "",
      "### 수정됨 (Fixed)",
      "- **cli:** 기존 릴리스 항목 유지",
      ""
    ].join("\n"));

    const changed = syncChangelogRollovers({ rootDir: repo, version: "4.2.2", date: "2026-05-10" });
    const currentEnglish = readFileSync(join(repo, "CHANGELOG.md"), "utf8");
    const currentKorean = readFileSync(join(repo, "CHANGELOG.ko.md"), "utf8");

    assert.equal(changed, false);
    assert.match(currentEnglish, /### Fixed[\r\n-]+- \*\*cli:\*\* existing release note should stay\./);
    assert.match(currentKorean, /### 수정됨 \(Fixed\)[\r\n-]+- \*\*cli:\*\* 기존 릴리스 항목 유지/);
  });
});
